version: 2
project_name: gorepo

builds:
  - id: gorepo
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=vendor
    ldflags:
      - "-s -w"

universal_binaries:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_universal"
    source:
      - gorepo
    replacements:
      darwin_amd64: darwin_universal
      darwin_arm64: darwin_universal

release:
  prerelease: auto
  github:
    owner: gorepo-cli
    name: gorepo

brews:
  - name: gorepo
    owner: gorepo-cli
    repo: homebrew-gorepo
    commit_author:
      name: Goreleaser
      email: noreply@goreleaser.com
    description: "A cli to manage go monorepos"
    homepage: "https://github.com/gorepo-cli/gorepo"
    install: |
      bin.install "gorepo"

archives:
  - id: gorepo-archive
    format: tar.gz
    builds:
      - gorepo
