version: 2
project_name: gorepo

builds:
  - id: gorepo
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=vendor
    ldflags:
      - "-s -w"

universal_binaries:
  - id: gorepo-universal
    name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_universal"

release:
  prerelease: auto
  github:
    owner: gorepo-cli
    name: gorepo

brews:
  - name: gorepo
    commit_author:
      name: Goreleaser
      email: noreply@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    license: "MIT"
    description: "A cli to manage go monorepos"
    homepage: "https://github.com/gorepo-cli/gorepo"
    install: |
      bin.install "gorepo"
    # Repository to push the generated files to.
    repository:
      # Repository owner.
      #
      # Templates: allowed.
      owner: gorepo-cli

      # Repository name.
      #
      # Templates: allowed.
      name: homebrew-gorepo

      # Optionally a branch can be provided.
      #
      # Default: default repository branch.
      # Templates: allowed.
      branch: master

      # Optionally a token can be provided, if it differs from the token
      # provided to GoReleaser
      #
      # Templates: allowed.
      token: ${{ secrets.PUBLISHER_TOKEN }}

archives:
  - id: gorepo-archive
    format: tar.gz
    builds:
      - gorepo
